# Generated by Django 3.0.7 on 2020-08-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_max_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('No Category', ' No Category'), ('Home', 'Home'), ('Toys', 'Toys'), ('Tech', 'Tech'), ('Sport', 'Sport')], default='No Category', max_length=64),
        ),
    ]
