# Generated by Django 3.0.7 on 2020-08-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200812_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='max_bid',
            field=models.IntegerField(),
        ),
    ]
