# Generated by Django 3.0.7 on 2020-08-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200814_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='min_bid',
        ),
    ]
